---
# tasks file for httpd
- name: Install apache httpd
  ansible.builtin.apt:
    name: apache2
    state: present #present means install
    update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html #becuase index.html is in the same location as playbook stays
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'

